version: '3.8'

services:
  rsa-server:
    build: ./server
    container_name: rsa-server
    volumes:
      - ./keys:/app/keys
    ports:
      - "5000:5000"
    networks:
      - secure-net

  rsa-client-demo:
    build: ./client
    container_name: rsa-client
    depends_on:
      - rsa-server
    networks:
      - secure-net

networks:
  secure-net:
    driver: bridge